config/routes.rb
TodoExample::Application.routes.draw do
  resources :users do
    resources :todos do
    end
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_user

	def index
    @todos = @user.todos.all
  end

  def show
    @todo = @user.todos.find(params[:id])
  end

  def new
    @todo = @user.todos.new
  end

  def create
    @todo = @user.todos.new(todos_params)
    if @todo.save
      respond_to |format|
        format.html { redirect_to users_path }
    end
  end

  def edit 
    @todo = @user.todos.find(params[:id]) 
  end

  def update
    @todo = @user.todos.find(params[:id])
  end

  def destroy
    @todo = @user.todos.destory(params[:id])    
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

  def todos_params
    params.require(:todo).permit(:title, :description, :completed, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all  
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      respond_to do |format|
        format.html { redirect_to users_path }
      end
    end
  end

  def edit
    
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destory
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<% @users.each do |u| %>
	<%= u.firstname %>
	<%= u.lastname %>
	<%= u.email %>
	<br>
<% end %>
	
	<br>

<%= link_to "create new user",new_user_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.text_field :firstname %>
	<%= f.text_field :lastname %>
	<%= f.text_field :email %>
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= @user.firstname %>
<br>

<%= link_to "new todo",new_user_todo_path(@user) %>